name: Post repositories JSON
on:
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * *"

jobs:
  post-data-to-opseng-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - run: bundle config set without "development test"
      - run: bundle install
      - run: bin/post-data.sh
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          OPERATIONS_ENGINEERING_REPORTS_API_KEY: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_API_KEY }}
          OPERATIONS_ENGINEERING_REPORTS_HOST: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_HOST }}
      - uses: actions/upload-artifact@v2
        with:
          path: output.txt
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}