env:
  RUBY_VERSION: 3.0.2

name: Rspec tests
on: [push,pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
      - name: Run depedency audit
        run: |
          bundle exec bundler-audit